# Generated by Django 2.2.2 on 2019-06-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='secret',
            field=models.CharField(default='', max_length=30),
        ),
    ]
